---
- name: restart nscd
  become: true
  service:
    name: nscd
    state: restarted
    enabled: yes

- name: start nscd
  become: true
  service:
    name: nscd
    state: started
    enabled: yes