---
- name: Verify
  hosts: all

  tasks:
    - name: Gather service facts
      service_facts:

    - name: Verify that nscd is running
      assert:
        that: "ansible_facts.services['{{ item }}'] is defined and ansible_facts.services['{{ item }}'].state == 'running'"
      with_items:
        - nscd.service